### PR TITLE
add post build-a-standalone-executable

### PR DESCRIPTION
**Pull request by ers35**
I wrote a post about the [luastatic](https://github.com/ers35/luastatic) command line tool that builds a Lua program to a standalone executable.

### CODE REVIEW

**Comment by Etiene** [comment]
Wow, that is a very useful library! :D 
However, I think the post is a little bit too succinct... There was recently a discussion on the mailing list called "Two types of Lua programmer, or two types of Lua code?" and a big chunk of it is dedicated to using a Lua program as a standalone application. Have you seen it? I feel you could elaborate on some of those points discussed and then offer `luastatic` as a tool to help with that :) What do you think?

**Comment by ers35** [comment]
I found and read the [mailing list discussion](http://comments.gmane.org/gmane.comp.lang.lua.general/120641). luastatic does not handle downloading dependencies like LuaRocks. Perhaps [LuaRocks integration](https://github.com/keplerproject/luarocks/pull/264#issuecomment-149366037) makes sense in the long term.

Is there a particular area you feel I should expand on? I could give a complete example of building an application using [LuaSQLite3](http://lua.sqlite.org/index.cgi/home) and cross compiling it to Windows using MinGW. That would demonstrate more of luastatic's features.

**Comment by Etiene** [comment]
Yes, a more practical example would be amazing! But what I thought that could more elaborated was more of a theory/discussion on why this is an interesting tool. I felt the paragraph introducing it was too short :) It made the post feel too much of a "Hey, here is a library X that does Y, bye". Maybe you could talk a little about building Lua programs on different OS and then offer luastatic as a solution? Or maybe you could write about why you decided to write luastatic?

**Comment by ers35** [comment]
I rewrote the post with a more comprehensive example.

**Comment by Etiene** [comment]
Sorry for the delay on replying! I moved apartments last week ^.^

Thanks for your post! :D Merging!

**Pull request merged**
