### PR TITLE
adding luaenterprise

### PR DESCRIPTION
**Pull request by forkfork**
short article on introducing lua in an established team

### CODE REVIEW

**Comment by Etiene** [comment]
Hello :) Great post! 

General feedback before merging:

Could you add a little bit more information of you as an author? At least a picture and a small 1 sentence description, please? Maybe also 1 url of where to find you outside the Lua.Space universe? :) The picture doesn't have to be a photo of you. It could even be the same picture you're using for github :) 

About the post:
Is it possible to add a little bit more information about the company and the project, unless it's confidential? It's always a pleasure to know where Lua is being used :)
Could you elaborate a little more on the results of this technical move? Like adding some benchmark comparisons if you have and they can be shared? I also think maybe it would be great to know how long did it take to replace the node app with the Lua app...

**Comment by bogdanm** [comment]
Hi @forkfork,

That certainly looks like a good story, but it'd be great if you could provide more details, just like @Etiene said. For me, the most interesting part is this:

> This quick rewrite soon replaced the Node.js solution in production.

I'd really like to know more how a quick Lua rewrite replaced node.js in a production environment, because this is certainly something you don't hear every day :)

Thanks,
Bogdan

**Comment by undefdev** [comment]
Hi,

I believe this is really an interesting topic, and if you would add more detail to this post it could provide valuable insights for those intending to do the same.

It would be very interesting to read about some stuff in more detail:

You mention that your Lua solution performed much better. I think it would be interesting for our readers to know _how_ much better. Could you possibly provide benchmarks on the performance, preferably using a graph?

You also mention that it was _"a quick rewrite"_. Im curious on how much time and effort it actually took.
This is definitely something a lot of teams would like to know before considering switching over.

Thank you very much!

**Comment by forkfork** [comment]
Thanks for the feedback! I'll ad some more detail and context over the next couple of days.

**Comment by undefdev** [comment]
Glad to hear that, looking foward to it!

**Comment by Etiene** [comment]
awesome! can't wait ^___^

**Comment by Etiene** [comment]
Hello forkfork! Any news on an updated version of this post? :)

**Pull request closed without merging**
