### PR TITLE
Making music in Lua

### PR DESCRIPTION
**Pull request by elihugarret**
This is my post! :D I hope it is ok. Cheers!

### CODE REVIEW

**Comment by Etiene** [comment]
Hello, Elihu! Yay! I've been waiting for this post :dancer: 

It's a great introductory post, I can't wait for the next ones! 
I've found some tiny typos /grammar issues, but don't worry about it, I'll fix the ones I found after merge. 

On the conclusion, could you add one of your complete tracks before directing people to your soundcloud for the others? I think that'd be really interesting :)

**Comment by elihugarret** [comment]
Thank you Etiene, you are so cool!
I added one of my tracks. Let me know if there's something more to write.
Cheers!

**Comment by Etiene** [comment]
So far so good! I'm gonna wait more reviewers to give their input :+1:

**Comment by undefdev** [comment]
Hey,

I think that's pretty damn cool, I always wanted to make music with Lua!

It's just a pity that this blog post only tells you that you can make music with Lua.
It doesn't tell me much about Moonlet's usage (there doesn't seem to be documentation for it yet on Github) or gives me hints about how to make something like it on my own.
So in my case you rather got me interested in Worp to be honest :)

That's fine, but it might leave some readers frustrated who want to try out Moonlet right away.
So if you're interested in other people using Moonlet as well, it might be a good idea to write some basic introduction about it's usage in this blog post already.

It's your call though, I wouldn't object releasing the post as it is.

**Comment by elihugarret** [comment]
Hi!
Yes, this post is just only for showing that music with Lua is possible. Now I'm writing the next post and it will be about Moonlet and all the technical details. The documentation is almost ready and I want this post to be more like a preview.
:D Worp is great for audio processing!

**Pull request merged**
